print("###########Address Form####################")
L1=input("Enter the Door Number and House Name   ==>")
L2=input("Enter The Street name                  ==>")
L3=input("Enter the Area Name and City Name      ==>")
L4=input("Enter The Pincode                      ==>")
print("###################Address###################")
print(L1+',')
print(L2+',')
print(L3+',')
print('PINCODE:',L4)